name: Export ADF ARM Templates

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:  # Allow manual trigger in GitHub UI

jobs:
  export-adf-arm:
    runs-on: ubuntu-latest

    env:
      DATA_FACTORY_NAME: ${{ secrets.ADF_NAME }}  # Define this in GitHub Secrets
      SOURCE_FOLDER: .  # Root of repo contains ADF folders
      OUTPUT_FOLDER: adf_artifacts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install ADF Utilities
        run: npm install -g @microsoft/azure-data-factory-utilities

      - name: Validate ADF source JSON
        run: adf validate --rootFolder $SOURCE_FOLDER

      - name: Export ARM templates
        run: |
          mkdir -p $OUTPUT_FOLDER
          adf publish \
            --rootFolder $SOURCE_FOLDER \
            --outputFolder $OUTPUT_FOLDER \
            --dataFactoryName $DATA_FACTORY_NAME

      - name: Upload ARM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: adf-arm-templates
          path: ${{ env.OUTPUT_FOLDER }}
